import { PrismaClient } from "@prisma/client";

const templates = [
  // ── Kitchen ──────────────────────────────────────────────────────
  {
    type: "BASE_CABINET",
    label: "Base cabinet",
    category: "kitchen",
    shelves: 1,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.6,
    finishMult: 1.1,
    edgeBandMult: 18,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: {},
  },
  {
    type: "WALL_CABINET",
    label: "Wall cabinet",
    category: "kitchen",
    shelves: 1,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    heightDefault: 2.4,
    depthDefault: 1.5,
    plywoodMult: 1.4,
    finishMult: 1.0,
    edgeBandMult: 16,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: {},
  },
  {
    type: "TALL_UNIT",
    label: "Tall unit",
    category: "kitchen",
    shelves: 4,
    doors: 2,
    drawers: 2,
    shutterMode: "HINGED",
    heightDefault: 7.5,
    plywoodMult: 2.2,
    finishMult: 1.6,
    edgeBandMult: 28,
    hardware: {
      "Soft Close Hinges": 8,
      Handles: 4,
      "Drawer Channels": 2,
      "Magnetic Catch": 2,
    },
    accessories: {},
  },
  {
    type: "CORNER_UNIT",
    label: "Corner unit",
    category: "kitchen",
    widthMin: 2.8,
    widthMax: 3.5,
    shelves: 2,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.8,
    finishMult: 1.2,
    edgeBandMult: 22,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: { "Corner joint fittings": 1 },
  },
  {
    type: "SINK_CABINET",
    label: "Sink cabinet",
    category: "kitchen",
    shelves: 0,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.3,
    finishMult: 0.9,
    edgeBandMult: 14,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: { "Moisture liner": 4 }, // sqft — calculator scales by depth
  },
  {
    type: "DRAWER_UNIT",
    label: "Drawer unit",
    category: "kitchen",
    shelves: 0,
    doors: 1,
    drawers: 3,
    shutterMode: "HINGED",
    plywoodMult: 1.5,
    finishMult: 1.0,
    edgeBandMult: 16,
    hardware: { "Soft Close Hinges": 2, Handles: 4, "Drawer Channels": 3 },
    accessories: {},
  },
  {
    type: "ISLAND_UNIT",
    label: "Island prep unit",
    category: "kitchen",
    widthMin: 4.0,
    widthMax: 5.5,
    shelves: 2,
    doors: 4,
    drawers: 2,
    shutterMode: "HINGED",
    plywoodMult: 2.4,
    finishMult: 1.8,
    edgeBandMult: 36,
    hardware: {
      "Soft Close Hinges": 8,
      Handles: 6,
      "Drawer Channels": 2,
      "Magnetic Catch": 2,
    },
    accessories: { "Island support frame": 1 },
  },
  {
    type: "ACCESSORY_UNIT",
    label: "Basket stack",
    category: "kitchen",
    shelves: 0,
    doors: 1,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.2,
    finishMult: 0.8,
    edgeBandMult: 12,
    hardware: { "Soft Close Hinges": 2, Handles: 1, "Magnetic Catch": 1 },
    accessories: { "Kitchen Basket": 3 },
  },

  // ── Wardrobe ─────────────────────────────────────────────────────
  {
    type: "DOUBLE_DOOR_SECTION",
    label: "Double door section",
    category: "wardrobe",
    widthMin: 2.4,
    widthMax: 3.2,
    shelves: 3,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.7,
    finishMult: 1.3,
    edgeBandMult: 22,
    hardware: { "Soft Close Hinges": 6, Handles: 2, "Magnetic Catch": 1 },
    accessories: {},
  },
  {
    type: "DRAWER_SECTION",
    label: "Drawer section",
    category: "wardrobe",
    shelves: 2,
    doors: 1,
    drawers: 3,
    shutterMode: "HINGED",
    plywoodMult: 1.6,
    finishMult: 1.1,
    edgeBandMult: 18,
    hardware: { "Soft Close Hinges": 2, Handles: 4, "Drawer Channels": 3 },
    accessories: {},
  },
  {
    type: "HANG_SECTION",
    label: "Hanging section",
    category: "wardrobe",
    shelves: 1,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.4,
    finishMult: 1.0,
    edgeBandMult: 14,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: { "Hanging Rod": 1 },
  },
  {
    type: "SHELF_SECTION",
    label: "Shelf section",
    category: "wardrobe",
    shelves: 5,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    plywoodMult: 1.5,
    finishMult: 1.0,
    edgeBandMult: 16,
    hardware: {},
    accessories: {},
  },
  {
    type: "SLIDING_SECTION",
    label: "Sliding wardrobe section",
    category: "wardrobe",
    shelves: 3,
    doors: 2,
    drawers: 2,
    shutterMode: "SLIDING",
    plywoodMult: 1.8,
    finishMult: 1.4,
    edgeBandMult: 24,
    hardware: {
      "Sliding Track Set": 1,
      "Sliding Roller Set": 2,
      "Soft Stopper": 1,
    },
    accessories: {},
  },

  // ── TV Unit ───────────────────────────────────────────────────────
  {
    type: "BACK_PANEL",
    label: "TV back panel",
    category: "tv-unit",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    depthDefault: 0.17,
    plywoodMult: 1.05,
    finishMult: 1.05,
    edgeBandMult: 8,
    hardware: {},
    accessories: {},
  },
  {
    type: "FLOATING_CABINET",
    label: "Floating cabinet",
    category: "tv-unit",
    shelves: 1,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.4,
    finishMult: 1.0,
    edgeBandMult: 14,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: { "Wall Mounting Hardware": 1 },
  },
  {
    type: "OPEN_SHELF",
    label: "Display shelf",
    category: "tv-unit",
    shelves: 2,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    depthDefault: 1.0,
    plywoodMult: 1.1,
    finishMult: 0.9,
    edgeBandMult: 10,
    hardware: {},
    accessories: {},
  },
  {
    type: "LED_PANEL",
    label: "LED feature panel",
    category: "tv-unit",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    depthDefault: 0.17,
    plywoodMult: 0.2,
    finishMult: 0.2,
    edgeBandMult: 4,
    hardware: {},
    accessories: { "LED Channel": 2 },
  },

  // ── Study ─────────────────────────────────────────────────────────
  {
    type: "TABLE_TOP",
    label: "Table top",
    category: "study",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    heightDefault: 0.17,
    plywoodMult: 1.3,
    finishMult: 1.1,
    edgeBandMult: 10,
    hardware: {},
    accessories: {},
  },
  {
    type: "DRAWER_CABINET",
    label: "Drawer cabinet",
    category: "study",
    shelves: 1,
    doors: 1,
    drawers: 3,
    shutterMode: "HINGED",
    widthMin: 1.5,
    widthMax: 2.0,
    plywoodMult: 1.5,
    finishMult: 1.0,
    edgeBandMult: 16,
    hardware: { "Soft Close Hinges": 2, Handles: 4, "Drawer Channels": 3 },
    accessories: {},
  },
  {
    type: "BOOKSHELF",
    label: "Bookshelf",
    category: "study",
    shelves: 5,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    depthDefault: 1.0,
    plywoodMult: 1.5,
    finishMult: 1.0,
    edgeBandMult: 14,
    hardware: {},
    accessories: {},
  },
  {
    type: "CABLE_PANEL",
    label: "Cable management panel",
    category: "study",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    plywoodMult: 0.3,
    finishMult: 0.2,
    edgeBandMult: 4,
    hardware: {},
    accessories: { "Cable Grommet": 2, "Partition Panel": 6 },
  },

  // ── Office ────────────────────────────────────────────────────────
  {
    type: "WORKSTATION",
    label: "Workstation",
    category: "office",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    plywoodMult: 1.5,
    finishMult: 1.15,
    edgeBandMult: 16,
    hardware: {},
    accessories: { "Metal Frame": 1 },
  },
  {
    type: "STORAGE_CABINET",
    label: "Storage cabinet",
    category: "office",
    shelves: 4,
    doors: 2,
    drawers: 1,
    shutterMode: "HINGED",
    plywoodMult: 1.9,
    finishMult: 1.4,
    edgeBandMult: 24,
    hardware: {
      "Soft Close Hinges": 6,
      Handles: 3,
      "Drawer Channels": 1,
      "Magnetic Catch": 2,
    },
    accessories: {},
  },
  {
    type: "MEETING_TABLE",
    label: "Meeting table",
    category: "office",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    heightDefault: 0.17,
    plywoodMult: 1.4,
    finishMult: 1.1,
    edgeBandMult: 14,
    hardware: {},
    accessories: { "Metal Frame": 1 },
  },

  // ── Bedroom ───────────────────────────────────────────────────────
  {
    type: "BED_FRAME",
    label: "Bed frame",
    category: "bedroom",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    plywoodMult: 2.3,
    finishMult: 1.4,
    edgeBandMult: 28,
    hardware: {},
    accessories: {},
  },
  {
    type: "SIDE_TABLE",
    label: "Side table",
    category: "bedroom",
    widthMin: 1.2,
    widthMax: 1.8,
    shelves: 1,
    doors: 1,
    drawers: 1,
    shutterMode: "HINGED",
    plywoodMult: 1.4,
    finishMult: 1.0,
    edgeBandMult: 12,
    hardware: { "Soft Close Hinges": 2, Handles: 2, "Drawer Channels": 1 },
    accessories: {},
  },
  {
    type: "DRESSER_UNIT",
    label: "Dresser unit",
    category: "bedroom",
    shelves: 2,
    doors: 2,
    drawers: 2,
    shutterMode: "HINGED",
    plywoodMult: 1.8,
    finishMult: 1.3,
    edgeBandMult: 22,
    hardware: {
      "Soft Close Hinges": 6,
      Handles: 4,
      "Drawer Channels": 2,
      "Magnetic Catch": 1,
    },
    accessories: { Mirror: 1 },
  },
  {
    type: "LOFT_CABINET",
    label: "Loft cabinet",
    category: "bedroom",
    shelves: 1,
    doors: 2,
    drawers: 0,
    shutterMode: "HINGED",
    plywoodMult: 1.4,
    finishMult: 1.0,
    edgeBandMult: 14,
    hardware: { "Soft Close Hinges": 4, Handles: 2, "Magnetic Catch": 1 },
    accessories: {},
  },
  {
    type: "UPHOLSTERED_PANEL",
    label: "Upholstered headboard",
    category: "bedroom",
    shelves: 0,
    doors: 0,
    drawers: 0,
    shutterMode: "OPEN",
    plywoodMult: 1.05,
    finishMult: 0,
    edgeBandMult: 0,
    hardware: {},
    accessories: { "Fabric Upholstery": 6 },
  },
] as const;

export async function seedModuleTemplates(prisma: PrismaClient) {
  console.log("Seeding module templates...");
  for (const t of templates) {
    await prisma.moduleTemplate.upsert({
      where: { type: t.type },
      update: t,
      create: t,
    });
  }
  console.log(`Seeded ${templates.length} module templates.`);
}
