import { PrismaClient } from "@prisma/client";

const entries = [
  // ── Sheet prices (per sqft) ──────────────────────────────────────
  {
    key: "sheet.BUDGET.plywood",
    category: "SHEET",
    label: "Plywood — budget grade",
    value: 65,
    unit: "per sqft",
    notes: "Commercial ply, MR grade",
  },
  {
    key: "sheet.BUDGET.surface",
    category: "SHEET",
    label: "Laminate finish — budget grade",
    value: 55,
    unit: "per sqft",
    notes: "Basic laminate, 0.8mm",
  },
  {
    key: "sheet.STANDARD.plywood",
    category: "SHEET",
    label: "Plywood — standard grade",
    value: 95,
    unit: "per sqft",
    notes: "BWR grade, IS:303",
  },
  {
    key: "sheet.STANDARD.surface",
    category: "SHEET",
    label: "Laminate finish — standard grade",
    value: 65,
    unit: "per sqft",
    notes: "Standard laminate, 1mm",
  },
  {
    key: "sheet.PREMIUM.plywood",
    category: "SHEET",
    label: "Plywood — premium grade",
    value: 140,
    unit: "per sqft",
    notes: "BWP/HDHMR, IS:710",
  },
  {
    key: "sheet.PREMIUM.surface",
    category: "SHEET",
    label: "Laminate/veneer — premium grade",
    value: 180,
    unit: "per sqft",
    notes: "Veneer or acrylic finish",
  },

  // ── Hardware prices (per piece/set) ──────────────────────────────
  {
    key: "hardware.EDGE_BAND",
    category: "HARDWARE",
    label: "PVC edge band",
    value: 8,
    unit: "per rft",
    notes: "22mm pre-glued",
  },
  {
    key: "hardware.HINGE_SOFT_CLOSE",
    category: "HARDWARE",
    label: "Soft-close hinge",
    value: 180,
    unit: "per piece",
    notes: "Hettich / Hafele",
  },
  {
    key: "hardware.HINGE_NORMAL",
    category: "HARDWARE",
    label: "Standard hinge",
    value: 80,
    unit: "per piece",
    notes: "Budget grade",
  },
  {
    key: "hardware.HANDLE",
    category: "HARDWARE",
    label: "Cabinet handle",
    value: 150,
    unit: "per piece",
    notes: "Standard pull handle",
  },
  {
    key: "hardware.PROFILE_HANDLE",
    category: "HARDWARE",
    label: "Profile / J-pull handle",
    value: 350,
    unit: "per piece",
    notes: "Premium / handleless",
  },
  {
    key: "hardware.TELESCOPIC_CHANNEL",
    category: "HARDWARE",
    label: "Telescopic drawer channel",
    value: 450,
    unit: "per set",
    notes: "Full-extension, 45kg",
  },
  {
    key: "hardware.TANDEM_BOX",
    category: "HARDWARE",
    label: "Tandem box drawer system",
    value: 1800,
    unit: "per set",
    notes: "Hettich / Hafele premium",
  },
  {
    key: "hardware.MAGNETIC_CATCH",
    category: "HARDWARE",
    label: "Magnetic catch",
    value: 70,
    unit: "per piece",
  },
  {
    key: "hardware.SLIDING_TRACK_SET",
    category: "HARDWARE",
    label: "Sliding wardrobe track set",
    value: 3200,
    unit: "per set",
    notes: "Single panel pair",
  },
  {
    key: "hardware.SLIDING_ROLLER_SET",
    category: "HARDWARE",
    label: "Sliding roller set",
    value: 650,
    unit: "per set",
  },
  {
    key: "hardware.SOFT_STOPPER",
    category: "HARDWARE",
    label: "Soft-close stopper",
    value: 450,
    unit: "per set",
  },
  {
    key: "hardware.LED_CHANNEL",
    category: "HARDWARE",
    label: "LED aluminium channel",
    value: 550,
    unit: "per piece",
    notes: "With diffuser cover",
  },
  {
    key: "hardware.KITCHEN_BASKET",
    category: "HARDWARE",
    label: "SS kitchen basket",
    value: 1800,
    unit: "per piece",
    notes: "Pull-out, 304 grade",
  },
  {
    key: "hardware.CABLE_GROMMET",
    category: "HARDWARE",
    label: "Cable grommet",
    value: 250,
    unit: "per piece",
  },
  {
    key: "hardware.METAL_FRAME",
    category: "HARDWARE",
    label: "Metal frame (workstation)",
    value: 520,
    unit: "per set",
  },
  {
    key: "hardware.PARTITION_PANEL",
    category: "HARDWARE",
    label: "Partition panel",
    value: 110,
    unit: "per sqft",
  },
  {
    key: "hardware.MIRROR",
    category: "HARDWARE",
    label: "Mirror (dresser)",
    value: 2400,
    unit: "per piece",
    notes: "4mm, 3ft × 2ft approx",
  },
  {
    key: "hardware.FABRIC_UPHOLSTERY",
    category: "HARDWARE",
    label: "Fabric upholstery",
    value: 130,
    unit: "per sqft",
    notes: "Includes foam and fabric",
  },
  {
    key: "hardware.SCREWS_AND_NAILS",
    category: "HARDWARE",
    label: "Screws and nails (lot)",
    value: 1500,
    unit: "per lot",
    notes: "Per project",
  },
  {
    key: "hardware.ADHESIVE",
    category: "HARDWARE",
    label: "Adhesive (Fevicol)",
    value: 950,
    unit: "per lot",
    notes: "Per project",
  },

  // ── Rate percentages (as decimals: 0.26 = 26%) ──────────────────
  {
    key: "rate.labor",
    category: "RATE",
    label: "Labor rate",
    value: 0.26,
    unit: "percentage",
    notes: "As % of material + hardware cost",
  },
  {
    key: "rate.installation",
    category: "RATE",
    label: "Installation rate",
    value: 0.08,
    unit: "percentage",
  },
  {
    key: "rate.transport",
    category: "RATE",
    label: "Transport rate",
    value: 0.04,
    unit: "percentage",
  },
  {
    key: "rate.dealer",
    category: "RATE",
    label: "Dealer margin",
    value: 0.06,
    unit: "percentage",
  },
  {
    key: "rate.contractor",
    category: "RATE",
    label: "Contractor margin",
    value: 0.1,
    unit: "percentage",
  },
  {
    key: "rate.customer",
    category: "RATE",
    label: "Customer margin (quote range)",
    value: 0.18,
    unit: "percentage",
    notes: "Upper end of customer range",
  },
];

export async function seedPriceBook(prisma: PrismaClient) {
  console.log("Seeding price book...");
  for (const entry of entries) {
    await prisma.priceBookEntry.upsert({
      where: { key: entry.key },
      update: {
        value: entry.value,
        label: entry.label,
        notes: entry.notes ?? null,
      },
      create: entry,
    });
  }
  console.log(`Seeded ${entries.length} price book entries.`);
}
